version: '2.1'
services:
  npm-security:
    build: ./
    depends_on: 
      - rds
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - rds
    environment:
      - REDIS_URL=redis://rds:6379/0
      - NPM_PACKAGES_URL=https://registry.npmjs.org/
  
  rds:
    image: redis:latest
    expose: 
      - 6379
    ports:
      - 6333:6379